# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  bmtn:
services:
  caPlantForm:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-plantform
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.plantform.tigerwit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CAPLANTFORM_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.plantform.tigerwit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/plantform.tigerwit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerPlantForm
    networks:
      - bmtn

  caUser:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-user
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.user.tigerwit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CAUSER_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.user.tigerwit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/user.tigerwit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerUser
    networks:
      - bmtn

  orderer.tigerwit.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.tigerwit.com
    container_name: orderer.tigerwit.com
    networks:
      - bmtn

  peer0.plantform.tigerwit.com:
    container_name: peer0.plantform.tigerwit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.plantform.tigerwit.com
    networks:
      - bmtn

  peer1.org.tigerwit.com:
    container_name: peer1.plantform.tigerwit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.plantform.tigerwit.com
    networks:
      - bmtn

  peer0.user.tigerwit.com:
    container_name: peer0.user.tigerwit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.user.tigerwit.com
    networks:
      - bmtn

  peer1.user.tigerwit.com:
    container_name: peer1.user.tigerwit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.user.tigerwit.com
    networks:
      - bmtn